import test from "node:test";
import assert from "node:assert/strict";
import { SchemaBuilder } from "../src/core/SchemaBuilder.js";

test("getDesc(table) returns normalized SQL column structure", async () => {
  const executed = [];
  const adapter = {
    dialect: "pg",
    placeholder(i) { return `$${i}`; },
    async execute(qb) {
      const { sql, params } = qb.compile();
      executed.push({ sql, params, type: qb._type });
      if (/information_schema\.columns/i.test(sql)) {
        return [
          {
            column_name: "id",
            data_type: "integer",
            is_nullable: "NO",
            column_default: "nextval('users_id_seq'::regclass)",
            ordinal_position: 1,
            numeric_precision: 32,
            numeric_scale: 0,
          },
          {
            column_name: "email",
            data_type: "character varying",
            is_nullable: "YES",
            character_maximum_length: 255,
            ordinal_position: 2,
          },
        ];
      }
      return [];
    },
  };

  const desc = await new SchemaBuilder(adapter).getDesc("users", { schema: "public" });
  assert.equal(desc.kind, "table");
  assert.equal(desc.dialect, "pg");
  assert.equal(desc.name, "users");
  assert.equal(desc.schema, "public");
  assert.equal(desc.columns.length, 2);
  assert.equal(desc.columns[0].name, "id");
  assert.equal(desc.columns[0].nullable, false);
  assert.equal(desc.columns[1].name, "email");
  assert.equal(desc.columns[1].nullable, true);

  assert.equal(executed[0].type, "select");
  assert.match(executed[0].sql, /table_schema = \$1/i);
  assert.deepEqual(executed[0].params, ["public", "users"]);
});

test("getDesc(table) can include CREATE SQL script", async () => {
  const adapter = {
    dialect: "pg",
    placeholder(i) { return `$${i}`; },
    async execute(qb) {
      const { sql } = qb.compile();
      if (/information_schema\.columns/i.test(sql)) {
        return [
          {
            column_name: "id",
            data_type: "integer",
            is_nullable: "NO",
            column_default: "1",
            ordinal_position: 1,
          },
          {
            column_name: "email",
            data_type: "character varying",
            is_nullable: "YES",
            ordinal_position: 2,
          },
        ];
      }
      if (/pg_catalog\.pg_attribute/i.test(sql)) {
        return [
          {
            column_name: "id",
            column_type: "bigint",
            is_not_null: true,
            identity_kind: "d",
            ordinal_position: 1,
          },
          {
            column_name: "user_type",
            column_type: "character varying(20)",
            is_not_null: true,
            ordinal_position: 2,
          },
        ];
      }
      if (/pg_catalog\.pg_constraint/i.test(sql)) {
        return [{ constraint_name: "audit_auditlog_pkey", constraint_def: "PRIMARY KEY (id)" }];
      }
      return [];
    },
  };

  const desc = await new SchemaBuilder(adapter).getDesc("audit_auditlog", { schema: "public", includeCreateSql: true });
  assert.match(desc.createSql || "", /CREATE TABLE IF NOT EXISTS "public"\."audit_auditlog"/);
  assert.match(desc.createSql || "", /"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL/);
  assert.match(desc.createSql || "", /CONSTRAINT "audit_auditlog_pkey" PRIMARY KEY \(id\)/);
});

test("getDesc(database) returns SQL database structure", async () => {
  const adapter = {
    dialect: "mysql",
    placeholder() { return "?"; },
    async execute(qb) {
      const { sql } = qb.compile();
      if (/SELECT DATABASE\(\)/i.test(sql)) return [{ name: "appdb" }];
      if (/information_schema\.tables/i.test(sql)) return [{ name: "users" }, { name: "orders" }];
      if (/information_schema\.views/i.test(sql)) return [{ name: "active_users" }];
      return [];
    },
  };

  const desc = await new SchemaBuilder(adapter).getDesc();
  assert.equal(desc.kind, "database");
  assert.equal(desc.dialect, "mysql");
  assert.equal(desc.name, "appdb");
  assert.deepEqual(desc.tables, ["users", "orders"]);
  assert.deepEqual(desc.views, ["active_users"]);
});

test("getDesc(database) can include CREATE SQL script", async () => {
  const adapter = {
    dialect: "mysql",
    placeholder() { return "?"; },
    async execute(qb) {
      const { sql, params } = qb.compile();
      if (/SELECT DATABASE\(\)/i.test(sql)) return [{ name: "appdb" }];
      if (/information_schema\.tables/i.test(sql)) return [{ name: "users" }];
      if (/information_schema\.views/i.test(sql)) return [];
      if (/information_schema\.columns/i.test(sql)) {
        if (params?.[0] === "users") {
          return [{ column_name: "id", column_type: "INT", is_nullable: "NO", ordinal_position: 1 }];
        }
        return [];
      }
      return [];
    },
  };

  const desc = await new SchemaBuilder(adapter).getDesc("database", { includeCreateSql: true });
  assert.match(desc.createSql || "", /CREATE DATABASE `appdb`;/);
  assert.match(desc.createSql || "", /CREATE TABLE `users`/);
});

test("getDesc supports mongo table and database structure", async () => {
  const adapter = {
    dialect: "mongo",
    db: {
      databaseName: "framecraft",
      listCollections() {
        return {
          async toArray() {
            return [{ name: "users" }, { name: "logs" }];
          },
        };
      },
      admin() {
        return {
          async listDatabases() {
            return { databases: [{ name: "admin" }, { name: "framecraft" }] };
          },
        };
      },
      collection(name) {
        return {
          find() {
            const docs = (name === "users")
              ? [{ _id: 1, email: "a@x.com", profile: { country: "US" } }]
              : [];
            return {
              limit() { return this; },
              async toArray() { return docs; },
            };
          },
        };
      },
    },
  };

  const schema = new SchemaBuilder(adapter);

  const tableDesc = await schema.getDesc("table", { name: "users", sampleSize: 5 });
  assert.equal(tableDesc.kind, "table");
  assert.equal(tableDesc.name, "users");
  assert.ok(tableDesc.columns.some((c) => c.name === "email"));
  assert.ok(tableDesc.columns.some((c) => c.name === "profile.country"));

  const dbDesc = await schema.getDesc("database", { includeDatabases: true });
  assert.equal(dbDesc.kind, "database");
  assert.equal(dbDesc.name, "framecraft");
  assert.deepEqual(dbDesc.collections, ["logs", "users"]);
  assert.deepEqual(dbDesc.databases, ["admin", "framecraft"]);

  const tableWithSql = await schema.getDesc("users", { includeCreateSql: true });
  assert.equal(tableWithSql.createSql, "db.createCollection('users');");

  const dbWithSql = await schema.getDesc("database", { includeCreateSql: true });
  assert.match(dbWithSql.createSql || "", /db\.createCollection\('logs'\);/);
  assert.match(dbWithSql.createSql || "", /db\.createCollection\('users'\);/);
});

test("getDesc strict mode normalizes shape across dialects", async () => {
  const pgAdapter = {
    dialect: "pg",
    placeholder(i) { return `$${i}`; },
    async execute(qb) {
      const { sql } = qb.compile();
      if (/information_schema\.columns/i.test(sql)) {
        return [{ column_name: "id", data_type: "integer", is_nullable: "NO", ordinal_position: 1 }];
      }
      if (/current_database\(\)/i.test(sql)) return [{ name: "appdb", schema: "public" }];
      if (/pg_catalog\.pg_tables/i.test(sql)) return [{ name: "users" }];
      if (/information_schema\.views/i.test(sql)) return [{ name: "v_users" }];
      return [];
    },
  };

  const mongoAdapter = {
    dialect: "mongo",
    db: {
      databaseName: "framecraft",
      listCollections() {
        return {
          async toArray() { return [{ name: "users" }]; },
        };
      },
      admin() {
        return {
          async listDatabases() { return { databases: [{ name: "framecraft" }] }; },
        };
      },
      collection() {
        return {
          find() {
            return {
              limit() { return this; },
              async toArray() { return [{ _id: 1, email: "x@y.com" }]; },
            };
          },
        };
      },
    },
  };

  const pgSchema = new SchemaBuilder(pgAdapter);
  const mongoSchema = new SchemaBuilder(mongoAdapter);

  const pgTable = await pgSchema.getDesc("users", { strict: true, schema: "public" });
  const mongoTable = await mongoSchema.getDesc("users", { strict: true });
  assert.deepEqual(Object.keys(pgTable), Object.keys(mongoTable));
  assert.equal(pgTable.sampleSize, null);
  assert.equal(pgTable.sampledDocuments, null);
  assert.equal(mongoTable.sampleSize, 20);
  assert.equal(mongoTable.sampledDocuments, 1);
  assert.ok(Array.isArray(pgTable.columns[0].types));
  assert.ok(Array.isArray(mongoTable.columns[0].types));
  assert.equal(pgTable.createSql, null);
  assert.equal(mongoTable.createSql, null);

  const pgDb = await pgSchema.getDesc("database", { strict: true });
  const mongoDb = await mongoSchema.getDesc("database", { strict: true });
  assert.deepEqual(Object.keys(pgDb), Object.keys(mongoDb));
  assert.deepEqual(pgDb.tables, ["users"]);
  assert.deepEqual(pgDb.views, ["v_users"]);
  assert.deepEqual(mongoDb.tables, ["users"]);
  assert.deepEqual(mongoDb.views, []);
  assert.equal(pgDb.createSql, null);
  assert.equal(mongoDb.createSql, null);
});

test("getDesc strict mode keeps createSql when requested", async () => {
  const pgAdapter = {
    dialect: "pg",
    placeholder(i) { return `$${i}`; },
    async execute(qb) {
      const { sql } = qb.compile();
      if (/information_schema\.columns/i.test(sql)) {
        return [{ column_name: "id", data_type: "integer", is_nullable: "NO", ordinal_position: 1 }];
      }
      if (/current_database\(\)/i.test(sql)) return [{ name: "appdb", schema: "public" }];
      if (/pg_catalog\.pg_tables/i.test(sql)) return [{ name: "users" }];
      if (/information_schema\.views/i.test(sql)) return [];
      return [];
    },
  };

  const schema = new SchemaBuilder(pgAdapter);
  const table = await schema.getDesc("users", { strict: true, schema: "public", includeCreateSql: true });
  const db = await schema.getDesc("database", { strict: true, includeCreateSql: true });

  assert.match(table.createSql || "", /CREATE TABLE/);
  assert.match(db.createSql || "", /CREATE DATABASE/);
});
